from canc_type_pred import CancTypeClassTask
from deconv import DeconvTask
from survival_pred import SurvivalTask
from drug_sens_pred import DrugSensitivityTask
from prot_pred import ProteomePredTask
from components import EmbeddingPredHead