finetune:
  canc_type_class:
    tcga_data_dir: /path/to/tcga.h5ad
    pretrained_model_path: /path/to/your_model.ckpt
    batch_size: 64
    epochs: 10
    head_learning_rate: 1e-3
    hidden_dim: 128
    dropout: 0.1
    test_size: 0.2
    random_seed: 42
    normalized: true
    merge_gbm_lgg: true